name: cleanup caches by a branch
on:
  pull_request_target:
    types:
      - closed
  delete:
  workflow_dispatch:
    inputs:
      branchNames:
        description: "削除対象とするキャッシュのあるbranch(ref)のリスト"
        required: false
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        uses: 4m-mazi/souji-action@93c22ab7b90ed60f3563651dc72bad0027e4d657 # v1.4.1
        with:
          branch-names: ${{ inputs.branchNames }}
